"""
Trained Model Inference Engine for CMTSF-Net
============================================
Loads weights from `trained_model.json` generated by `train_model.py`.
Provides mathematical inference for:
- Spectral Score
- Prosodic Score
- Channel Score
- Gated Attention Fusion
- Calibrated 65% Inconclusive Threshold
"""

import os
import json
import math
from typing import Dict, Any, List, Tuple

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
WEIGHTS_FILE = os.path.join(BASE_DIR, "weights", "trained_model.json")


class TrainedVoiceClassifier:
    def __init__(self, weights_path: str = WEIGHTS_FILE):
        self.weights_path = weights_path
        self.is_loaded = False
        self.model_data: Dict[str, Any] = {}
        self.means: List[float] = []
        self.stds: List[float] = []
        self.weights: List[float] = []
        self.bias: float = 0.0
        self.threshold: float = 65.0
        self.load_model()

    def load_model(self):
        if os.path.exists(self.weights_path):
            try:
                with open(self.weights_path, "r") as f:
                    self.model_data = json.load(f)
                self.means = self.model_data["scaler"]["means"]
                self.stds = self.model_data["scaler"]["stds"]
                self.weights = self.model_data["classifier"]["weights"]
                self.bias = self.model_data["classifier"]["bias"]
                self.threshold = float(self.model_data.get("confidence_inconclusive_threshold", 65.0))
                self.is_loaded = True
                print(f"[TrainedVoiceClassifier] Loaded trained weights from {self.weights_path}")
            except Exception as e:
                print(f"[TrainedVoiceClassifier] Failed loading weights: {e}")
                self.is_loaded = False
        else:
            self.is_loaded = False

    def predict(self, feature_vector: List[float]) -> Dict[str, Any]:
        """
        Executes model inference:
        1. Scales features z = (x - mean) / std
        2. Computes modality-level contributions:
           - spectral_score (features 0..3)
           - prosodic_score (features 4..8)
           - channel_score  (features 9..11)
        3. Computes final ai_probability and human_probability via calibrated sigmoid
        4. Applies 65% inconclusive threshold decision logic
        """
        if not self.is_loaded:
            # Fallback if weights not found
            return {
                "human_probability": 0.5,
                "ai_probability": 0.5,
                "confidence": 50.0,
                "verdict": "Suspicious / Inconclusive",
                "risk_level": "Medium",
                "spectral_score": 0.5,
                "prosodic_score": 0.5,
                "channel_score": 0.5,
                "mode": "Demo Mode (Uncalibrated)",
                "is_trained": False
            }

        # Normalize features
        n_feats = min(len(feature_vector), len(self.weights), len(self.means))
        z_vector = []
        for i in range(n_feats):
            mean = self.means[i]
            std = self.stds[i] if self.stds[i] > 1e-9 else 1.0
            z_val = (feature_vector[i] - mean) / std
            z_vector.append(z_val)

        # Modality sub-scores (dot product with subgroup weights)
        spec_indices = [0, 1, 2, 3]
        pros_indices = [4, 5, 6, 7, 8]
        chan_indices = [9, 10, 11]

        def compute_subgroup_score(indices):
            sub_z = sum(self.weights[idx] * z_vector[idx] for idx in indices if idx < n_feats)
            sub_prob = 1.0 / (1.0 + math.exp(-max(-15.0, min(15.0, sub_z))))
            return round(sub_prob, 4)

        spectral_score = compute_subgroup_score(spec_indices)
        prosodic_score = compute_subgroup_score(pros_indices)
        channel_score = compute_subgroup_score(chan_indices)

        # Full linear logit
        full_z = sum(self.weights[i] * z_vector[i] for i in range(n_feats)) + self.bias
        ai_prob = 1.0 / (1.0 + math.exp(-max(-15.0, min(15.0, full_z))))
        human_prob = 1.0 - ai_prob

        # Calibrate confidence
        confidence = round(max(human_prob, ai_prob) * 100.0, 1)

        # 65% Inconclusive Threshold Rule
        if confidence < self.threshold:
            verdict = "Suspicious / Inconclusive"
            risk_level = "Medium"
        elif ai_prob > human_prob:
            verdict = "Likely AI-Generated Voice"
            risk_level = "Critical" if ai_prob >= 0.85 else "High"
        else:
            verdict = "Likely Human Voice"
            risk_level = "Low"

        return {
            "human_probability": round(human_prob, 4),
            "ai_probability": round(ai_prob, 4),
            "confidence": confidence,
            "verdict": verdict,
            "risk_level": risk_level,
            "spectral_score": spectral_score,
            "prosodic_score": prosodic_score,
            "channel_score": channel_score,
            "mode": "Trained Model",
            "is_trained": True
        }
